-- JumRok starter content: the homestay catalogue and blog posts.
--
-- Run AFTER schema.sql, in the Supabase Dashboard: SQL Editor > New query >
-- paste > Run. Safe to re-run: existing rows are updated in place.
--
-- These rows have no host_id/author_id — they belong to the platform, not to
-- a host account — and go straight in as 'approved' so the site has content
-- from day one. The SQL Editor bypasses RLS, which is what allows that.

-- ---- Listings --------------------------------------------------------------
insert into public.listings (
  id, status, host_id, name, tagline, description, images, thumbnail_url, region, area, category, tags, price_amount, price_currency, price_unit, rating_score, review_count, max_guests, beds, room_type, room_size_value, room_size_unit, facilities, experiences, host_name, host_avatar_url, reviewed_at
)
values
  ('preah-village-homestay', 'approved', null, 'Preah Village Homestay', 'Local meals · Village life', 'Stay with a welcoming family in a traditional wooden stilt house on the outskirts of Siem Reap. Share home-cooked Khmer meals and evening stories on the veranda.', array['https://images.unsplash.com/photo-1628194968194-5189a8b51909?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1634623391440-eee532636511?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1672833474987-d50e626b7f3d?auto=format&fit=crop&w=1600&q=82']::text[], 'https://images.unsplash.com/photo-1628194968194-5189a8b51909?auto=format&fit=crop&w=800&q=80', 'Siem Reap', 'Angkor Countryside', 'Village Homestay', array['Rural & Countryside', 'Family-run']::text[], 18, 'USD', 'night', 4.7, 41, 3, 2, 'Private stilt house room', 18, 'sqm', array['WiFi', 'Parking', 'Fan', 'Shared bathroom']::text[], array['Home-cooked meals', 'Village walk', 'Traditional weaving demo']::text[], 'Sokha Ven', 'https://images.example.com/hosts/sokha-ven.jpg', now()),
  ('mekong-riverside-homestay', 'approved', null, 'Mekong Riverside Homestay', 'River view · Boat trips', 'Wake up to the sound of the Mekong. This riverside home in Kampong Cham offers a private room, sunset boat rides, and fresh river fish for dinner.', array['https://images.unsplash.com/photo-1634623391440-eee532636511?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1672833474987-d50e626b7f3d?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1645791973923-0a64f698d6ef?auto=format&fit=crop&w=1600&q=82']::text[], 'https://images.unsplash.com/photo-1634623391440-eee532636511?auto=format&fit=crop&w=800&q=80', 'Kampong Cham', 'Mekong Riverbank', 'Riverside Homestay', array['Rural & Countryside', 'Riverside']::text[], 22, 'USD', 'night', 4.8, 57, 4, 3, 'Riverfront private room', 22, 'sqm', array['WiFi', 'Parking', 'Hot water', 'Kitchen access']::text[], array['Sunset boat ride', 'River fishing', 'Home-cooked meals']::text[], 'Bunthoeun Chea', 'https://images.example.com/hosts/bunthoeun-chea.jpg', now()),
  ('rice-field-homestay', 'approved', null, 'Rice Field Homestay', 'Farm experience · Open views', 'Live and work alongside a farming family in Battambang. Try your hand at planting rice, milking cows, and cooking with ingredients straight from the field.', array['https://images.unsplash.com/photo-1672833474987-d50e626b7f3d?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1645791973923-0a64f698d6ef?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1770850994002-718c87787ce5?auto=format&fit=crop&w=1600&q=82']::text[], 'https://images.unsplash.com/photo-1672833474987-d50e626b7f3d?auto=format&fit=crop&w=800&q=80', 'Battambang', 'Rice Field Country', 'Farm Homestay', array['Rural & Countryside', 'Farm experience']::text[], 20, 'USD', 'night', 4.6, 33, 5, 4, 'Farmhouse shared room', 28, 'sqm', array['WiFi', 'Parking', 'Fan', 'Shared bathroom']::text[], array['Rice planting', 'Farm tour', 'Home-cooked meals']::text[], 'Ratanak Sor', 'https://images.example.com/hosts/ratanak-sor.jpg', now()),
  ('kampot-plantation-homestay', 'approved', null, 'Kampot Plantation Homestay', 'Pepper farm · Countryside air', 'Nestled among Kampot''s famous pepper plantations, this homestay lets you tour the farm, sample fresh pepper, and relax in the cool countryside air.', array['https://images.unsplash.com/photo-1645791973923-0a64f698d6ef?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1770850994002-718c87787ce5?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1774846505579-4a710ff4c5fe?auto=format&fit=crop&w=1600&q=82']::text[], 'https://images.unsplash.com/photo-1645791973923-0a64f698d6ef?auto=format&fit=crop&w=800&q=80', 'Kampot', 'Pepper Farm District', 'Plantation Homestay', array['Rural & Countryside', 'Plantation']::text[], 24, 'USD', 'night', 4.9, 62, 2, 2, 'Private garden bungalow', 20, 'sqm', array['WiFi', 'Parking', 'Hot water', 'Air conditioning']::text[], array['Pepper farm tour', 'Bike rental', 'Home-cooked meals']::text[], 'Chenda Pich', 'https://images.example.com/hosts/chenda-pich.jpg', now()),
  ('sre-ambel-community-homestay', 'approved', null, 'Sre Ambel Community Homestay', 'River visit · Community life', 'A community-run homestay along the Sre Ambel river, offering an authentic look at coastal village life with river visits and shared community meals.', array['https://images.unsplash.com/photo-1770850994002-718c87787ce5?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1774846505579-4a710ff4c5fe?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1628194968194-5189a8b51909?auto=format&fit=crop&w=1600&q=82']::text[], 'https://images.unsplash.com/photo-1770850994002-718c87787ce5?auto=format&fit=crop&w=800&q=80', 'Koh Kong', 'Sre Ambel River', 'Community Homestay', array['Rural & Countryside', 'Community-run']::text[], 28, 'USD', 'night', 4.5, 24, 4, 3, 'Community house private room', 24, 'sqm', array['WiFi', 'Parking', 'Fan', 'Kitchen access']::text[], array['River visit', 'Community meal', 'Fishing trip']::text[], 'Vanna Keo', 'https://images.example.com/hosts/vanna-keo.jpg', now()),
  ('phnom-penh-countryside-stay', 'approved', null, 'Phnom Penh Countryside Stay', 'Local life · Quiet escape', 'Just outside the capital, this Kandal countryside home offers a quiet escape with easy access to Phnom Penh and a genuine taste of everyday rural life.', array['https://images.unsplash.com/photo-1774846505579-4a710ff4c5fe?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1628194968194-5189a8b51909?auto=format&fit=crop&w=1600&q=82', 'https://images.unsplash.com/photo-1634623391440-eee532636511?auto=format&fit=crop&w=1600&q=82']::text[], 'https://images.unsplash.com/photo-1774846505579-4a710ff4c5fe?auto=format&fit=crop&w=800&q=80', 'Kandal', 'Phnom Penh Countryside', 'Countryside Homestay', array['Rural & Countryside', 'Near capital']::text[], 19, 'USD', 'night', 4.6, 29, 3, 3, 'Private garden room', 19, 'sqm', array['WiFi', 'Parking', 'Hot water', 'Shared bathroom']::text[], array['Home-cooked meals', 'Bike rental', 'Local market visit']::text[], 'Dara Nhem', 'https://images.example.com/hosts/dara-nhem.jpg', now())
on conflict (id) do update set
  status = excluded.status,
  host_id = excluded.host_id,
  name = excluded.name,
  tagline = excluded.tagline,
  description = excluded.description,
  images = excluded.images,
  thumbnail_url = excluded.thumbnail_url,
  region = excluded.region,
  area = excluded.area,
  category = excluded.category,
  tags = excluded.tags,
  price_amount = excluded.price_amount,
  price_currency = excluded.price_currency,
  price_unit = excluded.price_unit,
  rating_score = excluded.rating_score,
  review_count = excluded.review_count,
  max_guests = excluded.max_guests,
  beds = excluded.beds,
  room_type = excluded.room_type,
  room_size_value = excluded.room_size_value,
  room_size_unit = excluded.room_size_unit,
  facilities = excluded.facilities,
  experiences = excluded.experiences,
  host_name = excluded.host_name,
  host_avatar_url = excluded.host_avatar_url,
  reviewed_at = excluded.reviewed_at;

-- ---- Blog posts ------------------------------------------------------------
insert into public.blog_posts (
  id, status, author_id, slug, title, excerpt, cover_image, category, tags, content, author_name, author_avatar_url, published_at, reviewed_at
)
values
  ('reasons-to-choose-a-homestay', 'approved', null, '5-reasons-to-choose-a-homestay-in-cambodia', '5 Reasons to Choose a Homestay Over a Hotel in Cambodia', 'Hotels get you a bed. A homestay gets you a family, a home-cooked meal, and a much better story to tell when you''re back home.', 'https://images.unsplash.com/photo-1628194968194-5189a8b51909?auto=format&fit=crop&w=1600&q=82', 'Travel Tips', array['Homestay', 'Cambodia', 'First-time Visitors']::text[], array['It''s easy to default to a hotel when you''re planning a trip — the booking is familiar, the photos are polished, and you know roughly what you''re getting. But in Cambodia, some of the best travel memories come from staying with a local family instead.', 'The first reason is simple: food. Homestay hosts cook the meals their own families eat, not a tourist-friendly version of it. You''ll likely eat better, and cheaper, than you would at any restaurant nearby.', 'Second, you get context. A host can tell you why the village is laid out the way it is, which market day is worth planning around, and which temple down the road nobody puts in the guidebooks.', 'Third, your money goes further into the local economy. A homestay''s nightly rate mostly stays with the family hosting you, rather than a hotel chain or booking platform.', 'Fourth, you slow down. Without a hotel lobby to retreat to, you end up on the porch in the evening, which is usually where the actual conversations happen.', 'And finally — it''s simply more memorable. Ask anyone who has done both, and the homestay is almost always the story they tell first.']::text[], 'Sopheak Chan', 'https://images.example.com/authors/sopheak-chan.jpg', '2026-09-10'::timestamptz, now()),
  ('guide-to-khmer-home-cooking', 'approved', null, 'a-guide-to-khmer-home-cooking', 'A Guide to Khmer Home Cooking You Won''t Find in Restaurants', 'Restaurant menus barely scratch the surface of Khmer cuisine. Here''s what''s actually simmering in a Cambodian family kitchen.', 'https://images.unsplash.com/photo-1634623391440-eee532636511?auto=format&fit=crop&w=1600&q=82', 'Food', array['Food', 'Culture', 'Cambodia']::text[], array['Amok gets all the attention on restaurant menus, and for good reason — but it''s really just the introduction to Khmer cooking, not the whole story.', 'In a home kitchen, meals are built around what''s fresh that morning: whatever the market had, whatever''s in season, whatever a neighbour just handed over the fence. There''s very little that comes from a package.', 'Prahok, the fermented fish paste that flavours much of Khmer cooking, is usually the first thing a guest notices and the last thing they expect to end up loving. It doesn''t show up much on tourist menus, but it''s the backbone of most family meals.', 'Rice is the constant. Everything else — a light soup, a stir-fry, a dipping sauce — is built around a pot of rice that''s usually already on the table before you sit down.', 'If you''re staying with a family, don''t be shy about asking to help in the kitchen. Most hosts are happy to show you, and it''s the fastest way to actually learn how a dish comes together instead of just eating it.']::text[], 'Lina Meas', 'https://images.example.com/authors/lina-meas.jpg', '2026-08-28'::timestamptz, now()),
  ('khmer-village-etiquette', 'approved', null, 'understanding-khmer-village-etiquette', 'Understanding Khmer Village Etiquette Before Your Stay', 'A few small customs go a long way toward being a welcome guest instead of an awkward one.', 'https://images.unsplash.com/photo-1672833474987-d50e626b7f3d?auto=format&fit=crop&w=1600&q=82', 'Culture', array['Culture', 'Etiquette', 'Homestay']::text[], array['Cambodian village life runs on a set of quiet customs that most guests never get told directly — but noticing and following them makes a real difference to how welcome you feel.', 'The traditional greeting, the sampeah, is a slight bow with palms pressed together. You''ll rarely be expected to get it exactly right, but attempting it is always appreciated.', 'Shoes come off before entering a home — look for the row of sandals by the door, and you''ll know before you''re told.', 'The head is considered the most sacred part of the body, and the feet the least — so avoid touching anyone''s head, and try not to point your feet at people or at a Buddha image.', 'Modesty matters more in villages than it might in Phnom Penh or Siem Reap''s tourist strip. Covering shoulders and knees, especially near a temple, is a safe default.', 'None of this is about getting everything perfect. Hosts understand you''re a visitor — the effort is what''s noticed and remembered.']::text[], 'Vibol Ung', 'https://images.example.com/authors/vibol-ung.jpg', '2026-08-15'::timestamptz, now()),
  ('siem-reap-beyond-angkor-wat', 'approved', null, 'siem-reap-beyond-angkor-wat', 'Siem Reap Beyond Angkor Wat: What Locals Actually Do', 'Angkor Wat deserves the hype, but it''s a fraction of what makes Siem Reap worth a longer stay.', 'https://images.unsplash.com/photo-1645791973923-0a64f698d6ef?auto=format&fit=crop&w=1600&q=82', 'Destinations', array['Siem Reap', 'Destinations', 'Cambodia']::text[], array['Most visitors give Siem Reap a day, maybe two, entirely dedicated to the temples. Locals will tell you that''s only half the trip.', 'The Angkor Night Market and Old Market are worth an unhurried evening — less for souvenirs, more for watching how the town actually operates after dark.', 'Just outside the city, the countryside opens up quickly. Rice paddies, small villages, and quiet dirt roads are a short tuk-tuk ride from the temple crowds.', 'Tonlé Sap Lake''s floating villages are a genuinely different side of Siem Reap province — homes, schools, and shops that rise and fall with the water level through the year.', 'And if you''re staying with a village homestay nearby, ask your host what they''d do with a free afternoon. It''s usually a better recommendation than anything in a guidebook.']::text[], 'Sokha Ven', 'https://images.example.com/authors/sokha-ven.jpg', '2026-07-30'::timestamptz, now()),
  ('life-on-the-mekong', 'approved', null, 'life-on-the-mekong-a-riverside-story', 'Life on the Mekong: A Riverside Story', 'The river isn''t scenery here — it''s the schedule, the livelihood, and the reason the village exists where it does.', 'https://images.unsplash.com/photo-1770850994002-718c87787ce5?auto=format&fit=crop&w=1600&q=82', 'Culture', array['Mekong', 'Culture', 'Riverside']::text[], array['In a riverside village along the Mekong, the day is set by the water more than the clock. Boats go out early, before the heat sets in, and come back with whatever the river gave up that morning.', 'Kids learn to swim before they''re steady on their feet on land. It''s less a skill taught deliberately than something absorbed from growing up a few steps from the bank.', 'Meals shift with the season — more fish when the river runs high, more vegetables from the garden when it recedes and the soil left behind is at its richest.', 'Staying in a homestay here usually means at least one evening boat ride, watching the sun go down over the water while someone explains which bend in the river holds the best fishing spot.', 'It''s a slower rhythm than city life, and a few days is usually enough to feel yourself adjust to it.']::text[], 'Bunthoeun Chea', 'https://images.example.com/authors/bunthoeun-chea.jpg', '2026-07-12'::timestamptz, now()),
  ('packing-for-a-cambodian-homestay', 'approved', null, 'packing-for-a-cambodian-homestay', 'What to Pack for a Cambodian Homestay', 'Village homestays don''t need a hotel-sized suitcase — here''s what''s actually worth bringing.', 'https://images.unsplash.com/photo-1774846505579-4a710ff4c5fe?auto=format&fit=crop&w=1600&q=82', 'Travel Tips', array['Packing', 'Travel Tips', 'Homestay']::text[], array['Homestays are usually simpler than hotels, so the packing list should be too. A light, quick-dry wardrobe covers most of the trip — Cambodia''s climate is warm and humid nearly year-round.', 'Modest clothing is worth prioritising over anything else: something that covers shoulders and knees will serve you well both in the village and at any temple you visit.', 'Bring a headlamp or small flashlight. Rural electricity can be inconsistent, and a bathroom trip at 2am is a lot easier with your hands free.', 'Cash matters more than cards outside the cities — small villages rarely have a way to take payment electronically.', 'Basic toiletries and any medication you need should come with you, since the nearest pharmacy might be a real drive from a rural homestay.', 'Beyond that, pack light. Almost everything else can be borrowed, bought locally, or simply done without for a few days.']::text[], 'Chenda Pich', 'https://images.example.com/authors/chenda-pich.jpg', '2026-06-28'::timestamptz, now())
on conflict (id) do update set
  status = excluded.status,
  author_id = excluded.author_id,
  slug = excluded.slug,
  title = excluded.title,
  excerpt = excluded.excerpt,
  cover_image = excluded.cover_image,
  category = excluded.category,
  tags = excluded.tags,
  content = excluded.content,
  author_name = excluded.author_name,
  author_avatar_url = excluded.author_avatar_url,
  published_at = excluded.published_at,
  reviewed_at = excluded.reviewed_at;
